### ISSUE TITLE
[suggestion] Apply the game's audio effects to the Walkies

### ISSUE THREAD

**Issue by Fummowo** [n33kos/AlwaysHearActiveWalkie#3]
Right now it just sounds the same as if you also had an active walkie in your inventory and I think it feels a little too cheaty.
It would be awesome if the same directional audio, muffling and doppler effects from players voices were also applied to active walkies not held by the client
I'm not sure how difficult this would be to implement but I believe other mods such as the Skinwalker mod have managed to do so.
It would also be nice to see this implemented into the spectators view aswell, so that they can hear the active walkies near the player they're spectating

I really love the idea of this mod, it should be a basegame feature :))

**Comment by pkustura** [comment]
I agree with the suggestion in principle; the reason it is not in the base game like this is either for balance reasons or because it was too hard to implement/resource intensive (or less generously, that it wasn't considered). There is a pull request "...fix spatial audio on dropped WTs," which begins to address this, suggesting it may be the former. If this is the case, and the PR works, I see no reason not to merge the PR in the spirit of the mod (balance be damned)

**Comment by n33kos** [comment]
Thanks for the suggestions @Fummowo, I'll look into them.

I agree it would be ideal if the audio were actually coming from the walkie talkie. As @pkustura mentioned, currently the vanilla game is handling player audio in the same way and I didn't want to try rewriting that system yet. I'll check out the mentioned PR and see if it soles the problem for us.

Regarding spectators I _think_ that was resolved in version 1.4.3. Testing of this mod is fairly tedious and its challenging to test edge cases in which many players are in different states at the same time. I haven't tested yet but I adjusted the code this this case in mind.
